version: '3.9'

services:
  db-video-cards:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db-video-cards
    ports:
      - "5444:5432"
    volumes:
      - db-video-cards-data:/var/lib/postgresql/data

volumes:
  db-video-cards-data: